version: '3.8'
services:
  php-apache:
    container_name: memory-php-apache
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - database

  database:
    container_name: memory-database
    image: 'mysql:latest'
    ports:
      - 3306
    volumes:
      - "./scripts/memory.sql:/docker-entrypoint-initdb.d/1.sql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: memory

  phpmyadmin:
    container_name: memory-phpmyadmin
    image: phpmyadmin
    restart: always
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
      PMA_HOST: database